weizheng1910/linkdr

- app/models/user_company.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20200218062817_devise_create_user_companies.rb
- db/schema.rb
- test/fixtures/user_companies.yml
- test/models/user_company_test.rb
Would like to add a company login / sign up, separate from the companices object / model
> Added devise user_company as company login

- app/models/user_candidate.rb
- config/routes.rb
- db/migrate/20200218063824_devise_create_user_candidates.rb
- test/fixtures/user_candidates.yml
- test/models/user_candidate_test.rb
Basic Devise initialisation for users / candidates
> Basic Devise for users / candidates

- app/controllers/companies_controller.rb
- app/models/company.rb
- app/models/user_company.rb
- app/views/companies/edit.html.erb
- app/views/companies/new.html.erb
- app/views/companies/show.html.erb
- config/routes.rb
- db/migrate/20200218064300_companies.rb
- db/schema.rb
> crud for companies. linked companies to user_companies

- app/controllers/concerns/accessible.rb
- app/controllers/user_candidates/registrations_controller.rb
- app/models/candidate.rb
- app/models/user_candidate.rb
- config/routes.rb
- db/migrate/20200218091640_add_user_candidate_id_to_candidates.rb
- db/schema.rb
This automatically creates a candidate object when they create a user_candidate (make a new candidate account in Devise)
> Marry candidates and their profile

- app/assets/stylesheets/form.scss
- app/assets/stylesheets/jobs.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/user_companies/registrations/new.html.erb
- db/schema.rb
> updated form styling some more

- app/assets/javascripts/candidates.js
- app/assets/stylesheets/candidates.scss
- app/controllers/application_controller.rb
- app/controllers/candidates_controller.rb
- app/controllers/concerns/accessible.rb
- app/controllers/user_candidates/registrations_controller.rb
- app/controllers/user_candidates/sessions_controller.rb
- app/helpers/candidates_helper.rb
- app/views/candidates/create.html.erb
- app/views/candidates/destroy.html.erb
- app/views/candidates/edit.html.erb
- app/views/candidates/index.html.erb
- app/views/candidates/new.html.erb
- app/views/candidates/show.html.erb
- app/views/candidates/update.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/candidates_controller_test.rb
1. URL for candidate sign in is now in singular form: candidate/sign_in 
Plural form will be used for the profile, i.e. candidates/:id , candidates/:id/edit 
2. Added candidates edit form 
3. Added candidates display form 
4. Redirect for sign_in is in controllers/accessible.rb
5. Redirect for sign_up is in controllers/registration_controllers.rb
> Created controllers,views for candidates and linked signed up to candidates profile page

- app/models/candidate.rb
- app/models/job.rb
- app/models/match.rb
- app/models/skill.rb
- db/migrate/20200219021852_create_matches.rb
- db/migrate/20200219025327_jobs_skills.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/matches.yml
- test/models/match_test.rb
Add matches table and seed our first company, candidate, skill and job.
> Add matches table

- app/assets/stylesheets/home.scss
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- app/views/user_companies/sessions/new.html.erb
- db/schema.rb
> index urls plus login forms

- app/assets/stylesheets/scaffolds.scss
- app/views/layouts/application.html.erb
- app/views/user_candidates/registrations/new.html.erb
- app/views/user_candidates/sessions/new.html.erb
comments appreciated on how it looks!
> wowzers i updated the footer

- app/views/layouts/application.html.erb
> updated footer

- app/controllers/matches_controller.rb
- app/controllers/user_companies/registrations_controller.rb
- app/views/matches/companiesmatch.html.erb
- config/routes.rb
Employers can now view a job and see matching candidates in a lovely view.
> Match controller employer

- app/assets/stylesheets/home.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- app/views/user_companies/registrations/new.html.erb
- app/views/user_companies/shared/_links.html.erb
woops forgot to do pull request, updated nav bar and stuff
> Another css update

- app/assets/stylesheets/form.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/user_candidates/passwords/new.html.erb
- app/views/user_candidates/registrations/new.html.erb
- app/views/user_companies/passwords/new.html.erb
- app/views/user_companies/registrations/new.html.erb
- app/views/user_companies/shared/_links.html.erb
> updated forget password form

- app/assets/stylesheets/candidates.scss
- app/views/candidates/show.html.erb
> forget password form

- app/assets/stylesheets/candidates.scss
- app/views/candidates/show.html.erb
- app/views/layouts/application.html.erb
> @benjacoblee ---- candidate layout

- app/controllers/jobs_controller.rb
- app/models/company.rb
- app/models/job.rb
- app/views/jobs/_form.html.erb
- app/views/jobs/show.html.erb
- app/views/matches/companiesmatch.html.erb
- db/seeds.rb
REST routes for jobs partially done
> Res tful jobs

- app/assets/stylesheets/candidates.scss
- app/views/candidates/edit.html.erb
- app/views/candidates/show.html.erb
- app/views/layouts/application.html.erb
yay no merge conflicts! i added the candidates styling a bit. 
- waiting for suggested job matches for candidates
> candidates styling

- app/assets/stylesheets/candidates.scss
- app/assets/stylesheets/form.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/dashboard/show.html.erb
- app/views/jobs/_form.html.erb
- app/views/jobs/edit.html.erb
- app/views/jobs/index.html.erb
- app/views/jobs/new.html.erb
- app/views/layouts/application.html.erb
no merge conflict! updated navbar and jobs styling a bit
> jobs nav update

- app/assets/stylesheets/form.scss
- app/assets/stylesheets/jobs.scss
- app/views/companies/show.html.erb
- app/views/jobs/_form.html.erb
- app/views/jobs/edit.html.erb
- app/views/jobs/index.html.erb
- app/views/jobs/new.html.erb
- app/views/jobs/show.html.erb
- app/views/layouts/application.html.erb
another batch of css updates 
**job listings**
- actions section (view, edit, destroy) will always be at bottom of card 
- updated javascript random for header background
> yar more form styling updates!

- app/views/dashboard/show.html.erb
- app/views/jobs/show.html.erb
- app/views/layouts/application.html.erb
> updated nav drop down links

- app/assets/stylesheets/candidates.scss
- app/assets/stylesheets/jobs.scss
- app/controllers/dashboard_controller.rb
- app/views/dashboard/index.html.erb
- app/views/dashboard/show.html.erb
- app/views/jobs/index.html.erb
> **dashboard fixes

- app/assets/stylesheets/candidates.scss
- app/assets/stylesheets/jobs.scss
- app/views/candidates/edit.html.erb
- app/views/dashboard/show.html.erb
- app/views/jobs/edit.html.erb
- app/views/jobs/new.html.erb
- app/views/jobs/show.html.erb
- app/views/matches/candidatesmatch.html.erb
- app/views/matches/companiesmatch.html.erb
> MOAR CSS!!!!!

- app/views/jobs/index.html.erb
we have a million conditionals woopy!
> updated conditionals

- app/controllers/candidates_controller.rb
- app/controllers/jobs_controller.rb
- app/controllers/matches_controller.rb
- config/routes.rb
hi, i changed the code quite a bit for the candidates controller. it loops through matches to check if both parties have been liked, and only then can view candidate profile. @LaustinSpayce, could you review and see if it makes any sense? i'm not sure if the logic is correct
> Logic for matches

- app/assets/stylesheets/candidates.scss
- app/views/candidates/show.html.erb
finalized layout of candidate profile page after match
> very sexy update

- app/assets/stylesheets/candidates.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/candidates/edit.html.erb
- app/views/dashboard/show.html.erb
> sexy candidate edit form and dashboard page

- app/assets/stylesheets/form.scss
- app/assets/stylesheets/home.scss
- app/views/candidates/edit.html.erb
- app/views/dashboard/show.html.erb
- app/views/jobs/_form.html.erb
- app/views/jobs/index.html.erb
- app/views/jobs/show.html.erb
updated form fields to be required? maybe?
but confirm salary field is only in numbers
> sexy validations

- app/views/candidates/edit.html.erb
- app/views/jobs/_form.html.erb
used a javascript check for max skills
5 in jobs and 10 in candidates
> skills validation in jobs & candidates form

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/jobs_controller.rb
- app/helpers/application_helper.rb
- app/views/dashboard/show.html.erb
- app/views/jobs/index.html.erb
- config/initializers/pagy.rb
Adding pagination using the pagy gem. How handy
> Add pagination

- app/controllers/jobs_controller.rb
> Refactor jobs controller

- app/views/candidates/show.html.erb
At the page displayed upon successful matching, I added a link which redirects the company_user back to page where they can continue looking through and liking more candidates.
> Added link to redirect back to the page which allows the company to see more potential candidates for the role

- app/controllers/dashboard_controller.rb
- app/controllers/jobs_controller.rb
- app/views/jobs/index.html.erb
Jobs now vanish from all listings if you are rejected, or if you have rejected a job. Hurrah
> Join tables & Add "applied" pill on jobs page,

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/channels/room_channel.js
- app/controllers/candidates_controller.rb
- app/controllers/companies_controller.rb
- app/controllers/rooms_controller.rb
- app/controllers/user_candidates/registrations_controller.rb
Unauthorised users will be redirected back to the dashboard
> Room authentication

- app/assets/stylesheets/jobs.scss
- app/assets/stylesheets/room_messages.scss
- app/assets/stylesheets/scaffolds.scss
- app/views/dashboard/show.html.erb
- app/views/jobs/index.html.erb
- app/views/matches/index.html.erb
- app/views/rooms/show.html.erb
> updated boostrap listings from FLEX to cols
